#!/usr/bin/env python3
import os
import sys
from platform import system
VERSION = "0.1"
APPNAME = "macALR"

# Check if the operating system is Darwin (macOS)
if system() != "Darwin":
    print(f"{APPNAME}: Fatal: {APPNAME} is made for macOS. {APPNAME} detected you are not running Darwin")
    exit()

# Check of input file specified
try:
    file_name = str(sys.argv[1])
except Exception:
    print(f"{APPNAME}: Fatal: No input file specified")
    exit()

if sys.argv[1] == "-h":
	print(f"\nusage: {APPNAME} [input file]")
	print(f"       or {APPNAME} -h for this help screen\n")
	print(f"       or {APPNAME} -v for this version information\n")
	print("information: The given input should include the extension such as '.asm' or '.s'")
	print("             This program uses 'nasm' for compilation, 'ld' for linking and './' for executing")
	print("             There are no options or arguments that this program takes other than the input file")
	print(f"             {APPNAME} uses options specifically for macosx systems")
	print(f"             {APPNAME} requires that input assembly files be x86-64 (x64) compatible and syscalls be written for macosx systems\n")
	exit()
elif sys.argv[1] == "-v":
	print(f"{APPNAME} version {VERSION}")
	exit()

# Check if input file can be found
if os.path.isfile(f"{file_name}") == False:
    print(f"{APPNAME}: Fatal: Input file cannot be found")
    exit()

# First run NASM then check if it worked
os.system(f"nasm -f macho64 {file_name} -o output.o")
if os.path.isfile("output.o") == False:
    print(f"{APPNAME}: Fatal: NASM compiling failed")
    exit()

# Next run ld then check if it worked
os.system(f"ld -macosx_version_min 10.7.0 -o output -no_pie output.o")
if os.path.isfile(file_name) == False:
    print(f"{APPNAME}: Fatal: ld linking failed")
    os.remove(f"output.o")
    exit()

# Lastly run the executable. We cannot check of it worked
os.system(f"./output")

# Deletes object and executable files after running.
os.remove("output")
os.remove("output.o")
