#!/usr/bin/env python3
import os
import shutil
import sys
import subprocess
path = "~/bin"

# Check the OS
if sys.platform != "darwin":
  print("You do not seem to be running macOS. macALR is made for macOS and will not work on other operating systems without modification to code")
  exit(1)

# Check if nasm is installed
subprocess.Popen("nasm", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
if subprocess.check_output("echo $?", stderr = subprocess.STDOUT, shell = True) != b'0\n':
  print("macALRinstaller: Installation failed, nasm is not installed")

if not os.path.exists(path):
    os.makedirs(path)
shutil.copy("macALR", path)
os.system("chmod +x ~/bin/macALR")
if subprocess.check_output("macALR", stderr = subprocess.STDOUT, shell = True) == b'macALR: Fatal: No input file specified\n':
  print("macALRinstaller: Installed successfully")
else:
  print("macALRinstaller: Installation failed. You may want to read the INSTALLATION.md file for manual installation instructions")
  exit(1)
