.\" Manpage for macALR.
.\" Contact ileshkt@gmail.com to correct errors or typos.
.TH man 8 "29 May 2020" "1.0" "macALR man page"
.SH NAME
macALR, a shortcut/tool/script to make life easier for people getting into x86-64 assembly to quickly assemble, link and run in one command
.SH SYNOPSIS
To run macALR, type in 'macALR <path/to/file.extension or file.extension>'. To check the version, type in 'macALR -v'. There are no other options or arguments that macALR accepts
.SH DESCRIPTION
This program runs 'nasm' with the macho64 format. Then it links the file using 'ld' and sets the minimum macosx version to 10.7.0. Finally it runs the program using './'. To not clutter, it deletes the generated object and executable files.
.SH EXAMPLES
For this example, lets call the example file 'example.asm' with the path '~/assemblyPrograms/example.asm'. We assume that we are currently in the home directory. Running 'macALR example.asm' will not work as the file is not in the ~ directory. So we can type the path in by typing 'macALR ~/assemblyPrograms/example.asm'
.SH BUGS
There are no known bugs.
.SH AUTHOR
Ilesh Thiada (ileshkt@gmail.com)
